apiVersion: v1

kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  labels:
      app   : influxdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1

# What type? #
kind: Deployment
metadata:
  name: influxdb-deployment
  # Additional information #
  labels:
    project: influxdb
spec:
  # How many replicas? #
  replicas: 1
  # Whats pods to choose? #
  selector:
    # Choose with labels: #
    matchLabels:
      project: influxdb
  # Creating pods #
  template:
    metadata:
      # Additional information #
      labels:
          project: influxdb
    # Configs for containers #
    spec:
      # Include volume #
      volumes:
      - name: influxdb-volume
        persistentVolumeClaim:
          claimName: influxdb-pvc
      containers:
      - name: influxdb
        # Image to be used #
        image: influxdb:latest
        # Turn of DockerHub #
        imagePullPolicy: Never
        # Open ports #
        ports:
        - containerPort: 8086
        # Storage #
        volumeMounts:
        - mountPath: "/var/lib/influxdb"
          name: influxdb-volume
---
# Mandatory #
apiVersion: v1

# What type? #
kind: Service
metadata:
  name: influxdb-service
  labels:
      app  : influxdb
spec:
  # Access for other #
  type: ClusterIP
  # Access for what? #
  selector:
    project: influxdb
  ports:
    # Redirect ports from #
  - name: http
    port: 8086
    # Redirect port to #
    targetPort: 8086
